name: CI/CD to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes tools
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        az acr login --name umaia 
        az acr build --registry umaia --image nginx:${{ github.sha }}-${{ steps.date.outputs.date }} .

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Set AKS context
      run: |
        az aks get-credentials --resource-group Kubernetes --name umaiaCluster --overwrite-existing
    
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/nginx-deployment nginx=umaia.azurecr.io/nginx:${{ github.sha }}-${{ steps.date.outputs.date }}
        kubectl apply -f k8s/

